### ISSUE TITLE
integrate with LAVA

### ISSUE THREAD

**Issue by chombourger** [MentorEmbedded/mtda#11]

**Comment by hkoturap** [comment]
@chombourger ,
Will the Assist Board become the DUT for LAVA and complete target board control will be with Assist Board.
In this scenario updating the test suites result in LAVA when executed in Target board may be issue.

**Comment by chombourger** [comment]
the use case is somewhat similar to https://github.com/bootlin/lavabo
we may want LAVA to go through MTDA to power the board ON/OFF, write the OS image and get console output

**Comment by chombourger** [comment]
lava seems to support `to: flasher` which I believe could be used to issue `mtda storage commands`

**Comment by chombourger** [comment]
see https://staging.validation.linaro.org/scheduler/device/staging-soca9-01/devicedict and https://staging.validation.linaro.org/scheduler/job/262229/definition

**Comment by chombourger** [comment]
documentation added. available from f7ce42b5f45b7088fe4f467c55b1da04e8c925ca and later
