### ISSUE TITLE
configuration option to change prefix key

### ISSUE THREAD

**Issue by chombourger** [MentorEmbedded/mtda#4]
MTDA may be controlled from the interactive console by using a key combination of a prefix key, `Ctrl-a` by default, followed by a command key. People using a terminal multiplexer such as `screen` may find our default prefix key conflicting with the multiplexer. Provide a configuration option to change the default key prefix to any letter (e.g. `Ctrl-m`

**Comment by hkoturap** [comment]
@chombourger , 
Should the configuration option to change the default key prefix be provided in mtda.ini. Should all letters be taken care for configuration option(http://ascii-table.com/control-chars.php)

**Comment by chombourger** [comment]
@hkoturap let's start with letters and yes this would go in mtda.ini
